"""Unified attempts.tsv schema for the optimization harness.

Three writers (``auto_optimize.py``, ``control_loop.py``, and the
inline python heredoc in ``headless_remote.sh``) historically carried
their own field lists. This module exposes a single ``ATTEMPTS_FIELDNAMES``
list so every writer emits the same header.

The union is ordered by ``auto_optimize.py`` first, then fields that
only appear in the other two writers are appended in first-seen order.
``csv.DictWriter`` writes empty strings for missing keys, which is the
expected behavior for writers that do not populate every column.
"""

from __future__ import annotations


ATTEMPTS_FIELDNAMES: list[str] = [
    # auto_optimize.py order
    "rank",
    "kind",
    "policy_bucket",
    "experiment_kind",
    "lane",
    "target",
    "stack_members",
    "candidate_id",
    "patch_path",
    "touched_files",
    "hypothesis",
    "compare_result",
    "timing_summary",
    "semantic_risk",
    "timing_window_relation",
    "tail_cost",
    "total_work_change",
    "work_shifting_status",
    "stack_compatibility",
    "retry_condition",
    "sample_unit",
    "warm_or_cold",
    "samples_ms",
    "samples",
    "sample_count",
    "mean_ms",
    "mean_seconds",
    "median_ms",
    "median_seconds",
    "mad_ms",
    "mad_seconds",
    "iqr_ms",
    "iqr_seconds",
    "stdev_ms",
    "stdev_seconds",
    "range_ms",
    "range_seconds",
    "delta_ms",
    "delta_seconds",
    "change_class",
    "replicated",
    "timing_verdict",
    "timing_verdict_reason",
    "timing_verdict_method",
    "control_sample_count",
    "candidate_sample_count",
    "paired_sample_count",
    "control_samples_ms",
    "candidate_samples_ms",
    "paired_deltas_ms",
    "paired_deltas_seconds",
    "median_delta_ms",
    "median_delta_seconds",
    "bootstrap_ci_low_ms",
    "bootstrap_ci_high_ms",
    "bootstrap_ci_low_seconds",
    "bootstrap_ci_high_seconds",
    "permutation_p_value",
    "paired_stdev_ms",
    "paired_range_ms",
    "paired_mean_ms",
    "verdict",
    "correctness",
    "noise_flag",
    "stop_reason",
    "acceptance_policy",
    "evidence_status",
    "promotion_sample_floor",
    "bundle_audit_sample_floor",
    "notes",
    # Fields only present in control_loop.py / headless_remote.sh,
    # in first-seen order.
    "stage",
    "observed_cost_ms",
    "expected_delta_seconds",
    "p_owned",
    "p_safe",
    "p_gate",
    "p_local",
    "cost_attempt_seconds",
    "uncertainty",
    "lambda",
    "score_evidence",
    "ownership_confidence",
    "correctness_safety",
    "locality",
    "legacy_corl_score",
    "score",
    "recorded_at",
    "control_head",
    "control_median_ms",
    "control_median_seconds",
    # Confidence tier fields (B redesign, 2026-06-02).
    "confidence_tier",
    "confidence_margin_ms",
    "confidence_ci_width_ms",
    "confidence_decisiveness",
    "confidence_sign_consistency",
    # G2 decision constants (evidence schema).
    "delta_min_ms_used",
    "decisive_k",
    "sign_min",
    "escalation_steps",
    # G3 naive-k1 counterfactual.
    "naive_k1_first_delta_ms",
    "naive_k1_would_accept",
    # G4 environment fingerprint.
    "host_id",
    "env_class",
    "control_stdev_ms",
    "control_range_ms",
    # Detectability floor (2.14) — additive, verdict-neutral.
    "mde_ms",
    "power_at_observed_effect",
    # G5 generator provenance.
    "generator_model",
    "generator_session",
]


OPTIMIZATION_LEDGER_FIELDNAMES: list[str] = [
    "candidate_id",
    "lane",
    "judge_kind",
    "verdict",
    "naive_k1_would_accept",
    "naive_k1_first_delta_ms",
    "delta_min_ms_used",
    "decisive_k",
    "sign_min",
    "escalation_steps",
    "constants_hash",
    "host_id",
    "env_class",
    "control_stdev_ms",
    "control_range_ms",
    "generator_model",
    "generator_session",
    "replicated",
    "artifact_path",
    "recorded_at",
]
